spring.application.name=prev-maint-rpt
spring.main.web-application-type=none
spring.main.banner-mode=off
# 2) Set log levels as you like
logging.level.root=INFO
# 1) Write logs to this file
spring.jackson.mapper.accept-case-insensitive-properties=true
analysis.timeline=1 hour
#to prepare the zip file for preventive maintenance. Keep this value to true in customer environment.
prepare.json.preventive.maintenance=true
#to analyze the zip file prepared by prepare.json.preventive.maintenance. Keep this value to false in customer environment unless customer has access to ollama
prepare.report.preventive.maintenance=false
#number of parallel threads to be sent to AI server (use with caution. This will shootup GPU 3D)
prepare.report.preventive.maintenance.thread.pool.size=3
#to prepare the zip file for alarm analysis. Keep this value to true in customer environment.
prepare.json.alarm.analysis=true
#to analyze the zip file prepared by prepare.json.alarm.analysis. Keep this value to false in customer environment unless customer has access to ollama
prepare.report.alarm.analysis=false
zip.file.location=data
#-1 means unlimited. All historic measurement will be given to LLM. Set a limit of characters if you are running ollama in low end server
llm.data.size.limit=-1
#-1 means unlimited. All detailed diagnosis measurement will be given to LLM. Set a limit of characters if you are running ollama in low end server
llm.dd.size.limit=-1
# Ollama Configuration - not needed if prepare.alarm.analysis.report and prepare.kpi.compliance.report are set to false
ollama.enabled=true
ollama.api.url=http://localhost:11434/api/generate
ollama.model=gemma3:27b
ollama.temperature=0.4
ollama.max_tokens=2000000
