spring.application.name=prev-maint-rpt
spring.main.web-application-type=none
spring.main.banner-mode=off
# 2) Set log levels as you like
logging.level.root=INFO
# 1) Write logs to this file
spring.jackson.mapper.accept-case-insensitive-properties=true
analysis.timeline=1 hour
prepare.json.preventive.maintenance=true
prepare.report.preventive.maintenance=true
prepare.json.alarm.analysis=false
prepare.report.alarm.analysis=false
zip.file.location=data
llm.data.size.limit=-1
llm.dd.size.limit=-1
# Ollama Configuration
ollama.enabled=false
ollama.api.url=http://localhost:11434/api/generate
ollama.model=gemma3:12b
ollama.temperature=0.4
ollama.max_tokens=2000000
